base_url: https://jenkins-ci.org/
local_tz: UTC
base_title: Jenkins
generation:
  in_threads: 0
google_analytics:
  anonymizeIp: true
  account: UA-4216293-5
haml:
  :ugly: true
  :escape_html: false
asciidoctor:
  :safe: unsafe
  :base_dir: null
  :attributes:
    compat-mode: '@'
    attribute-missing: warn
    relfileprefix: '../'
    outfilesuffix: '/'
    idprefix: ''
    idseparator: '-'
    icons: font
    sectanchors: ''
    linkattrs: ''
    source-highlighter: coderay
    prewrap: null
